# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

 branches:
   except:
     - /-expt$/

before_script:
  - git config --global user.email "annakrystalli@googlemail.com"
  - git config --global user.name "annakrystalli"
